### ISSUE TITLE
Wrong Public IP or Multiple IP Address

### ISSUE THREAD

**Issue by vikas5914** [VirtuBox/ee-acme-sh#3]
Hi, 

Thanks for this awesome script, 

Recently I tried this script on multiple servers (Aws, Google Cloud and Digital Ocen) and The "**SERVER_PUBLIC_IP**" and "**DOMAIN_IP**" does not match. 

I use the command of SERVER_PUBLIC_IP and DOMAIN_IP and run them in SSH

The results : 

1) AWS Lightshell 

**SERVER_PUBLIC_IP**: 172.26.13.xxx
**DOMAIN_IP**:13.126.23x.x

2) Google Cloud 

**SERVER_PUBLIC_IP**: 10.128.0.x
**DOMAIN_IP**: 35.232.1xx.xx

3) Digital Ocen

**SERVER_PUBLIC_IP**: 138.197.46.xxx , 10.17.0.x
**DOMAIN_IP**: 138.197.46.xxx

https://github.com/VirtuBox/ee-acme-sh/blob/00cce8004c4023c48047fc333447ef33304ed93a/script/ee-acme.sh#L175

**Comment by vikas5914** [comment]
We can get Server Public IP using this : http://whatismyip.akamai.com/

**Comment by vikas5914** [comment]
@VirtuBox How about this fix: 

`SERVER_PUBLIC_IP=$(curl http://whatismyip.akamai.com/) `

I tried this on my server and it works.

**Comment by VirtuBox** [comment]
Hello @vikas5914,

I have published a new release (v2.1) which include the server public IP validation fix.

Regards,

**Comment by vikas5914** [comment]
@VirtuBox  Hi, 

I tested on two servers and its working (I used Easy Engine v3). However, there is an error:

The Nginx config at `/var/www/domina.tld/config/nginx/ssl.conf` is missing ssl_ciphers value.

**Comment by VirtuBox** [comment]
@vikas5914, if the ssl_ciphers directive is properly set in nginx.conf, there is no need to set it again in /var/www/domain.tld/conf/nginx/ssl.conf

**Comment by vikas5914** [comment]
@VirtuBox The nginx.conf has ssl_cipher. But still, it gives the error.  I think EE3 is setting the nginx.conf with wrong values. 

Here is the ssl part from nginx.conf created by EE3

```ssl_session_cache shared:SSL:20m;
ssl_session_timeout 10m;
ssl_prefer_server_ciphers on;
ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHADHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:AES128-GCM-SA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!ECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
```

**Comment by VirtuBox** [comment]
@vikas5914 You can try this one instead : 

```nginx
    # intermediate configuration. tweak to your needs.
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS';
    ssl_prefer_server_ciphers on;
```

Source : https://mozilla.github.io/server-side-tls/ssl-config-generator/

**Comment by vikas5914** [comment]
@VirtuBox  Hi, 

I have deleted `ssl_ciphers` from the all config file just to get the error again. But the site is still working fine. 

I am not sure why? 

Link: https://ssl.kapadiya.net/

**Comment by vikas5914** [comment]
Closing this issue since the main problem is fixed.
